// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzTodhd0v2scbiRdvtlFlHCQwGgZdReqU',
    appId: '1:539586696446:web:27148855ceaf58d731c1af',
    messagingSenderId: '539586696446',
    projectId: 'movies-601b2',
    authDomain: 'movies-601b2.firebaseapp.com',
    storageBucket: 'movies-601b2.firebasestorage.app',
    measurementId: 'G-G35T2HDKZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1AdTPjfOR4vCHJPOkBJcs36D65lcfI4U',
    appId: '1:539586696446:android:78ff5955fc57457431c1af',
    messagingSenderId: '539586696446',
    projectId: 'movies-601b2',
    storageBucket: 'movies-601b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzcn5_-kyMHpEo1n5hv_JqAIK6eubzxLE',
    appId: '1:539586696446:ios:36df84f03ffeddfe31c1af',
    messagingSenderId: '539586696446',
    projectId: 'movies-601b2',
    storageBucket: 'movies-601b2.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzcn5_-kyMHpEo1n5hv_JqAIK6eubzxLE',
    appId: '1:539586696446:ios:36df84f03ffeddfe31c1af',
    messagingSenderId: '539586696446',
    projectId: 'movies-601b2',
    storageBucket: 'movies-601b2.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzTodhd0v2scbiRdvtlFlHCQwGgZdReqU',
    appId: '1:539586696446:web:2448a728e56f1dd431c1af',
    messagingSenderId: '539586696446',
    projectId: 'movies-601b2',
    authDomain: 'movies-601b2.firebaseapp.com',
    storageBucket: 'movies-601b2.firebasestorage.app',
    measurementId: 'G-C2RRCPJ02G',
  );

}